On branch master
No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   .ipynb_checkpoints/News-Analyzer-checkpoint.ipynb
        new file:   .ipynb_checkpoints/Untitled-checkpoint.ipynb
        new file:   News_Analyzer.ipynb
        new file:   data/News_Category_Dataset_v3.json
        new file:   inference.py
        new file:   main.py
        new file:   tokenization.py

(news_analyzer_env) C:\Users\tnevi\multimodal_news_analyzer>git push origin master:main
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/evinatn/Multi-modal-news-analyzer.git'

(news_analyzer_env) C:\Users\tnevi\multimodal_news_analyzer>git branch -M main

(news_analyzer_env) C:\Users\tnevi\multimodal_news_analyzer>git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/evinatn/Multi-modal-news-analyzer.git' with '#' will be ignored, and an empty message aborts the commit.
t
exit
:wq
??